#!/usr/bin/env node

const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 8081 });


wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
  });

  ws.send('something');
});


process.stdin.resume();
process.stdin.setEncoding('utf8');
process.stdin.on('data', function(data) {
  process.stdout.write(data);
  wss.clients.forEach(function each(client) {
    client.send(data.toString());
  });  
});